### ISSUE TITLE
Знайди зображення подібне до цего

### ISSUE THREAD

**Issue by tjyha02** [tjyha02/pr5-veres_berezka-#1]
![default](https://cloud.githubusercontent.com/assets/23500113/20347132/64b48c18-ac08-11e6-9256-2654de70ec90.jpg)

**Comment by Sver4ok** [comment]
![novyy_rozdol_12](https://cloud.githubusercontent.com/assets/23500175/20347381/87072388-ac09-11e6-9d8f-2f9860b9dbb2.jpg)
